[package]
name = "linked_lists"
version = "0.1.7"
edition = "2021"
repository = "https://github.com/cod10129/linked_lists"
description = "Different types of linked lists."
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[features]
stack = []
persistent = []
persistent_arc = []
